apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.role }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
